"""empty message

Revision ID: 2ad7605c7d83
Revises: 47c76353265b
Create Date: 2022-02-08 20:33:58.897744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad7605c7d83'
down_revision = '47c76353265b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokeparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('hp', sa.String(length=50), nullable=True),
    sa.Column('defense', sa.String(length=50), nullable=True),
    sa.Column('attack', sa.String(length=50), nullable=True),
    sa.Column('ability_1', sa.String(length=50), nullable=True),
    sa.Column('ability_2', sa.String(length=50), nullable=True),
    sa.Column('ability_3', sa.String(length=50), nullable=True),
    sa.Column('sprite', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('poke_user_join',
    sa.Column('pokeparty_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokeparty_id'], ['pokeparty.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokeparty_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poke_user_join')
    op.drop_table('user')
    op.drop_table('pokeparty')
    # ### end Alembic commands ###
