"""empty message

Revision ID: 47c76353265b
Revises: 8208fdc3ea47
Create Date: 2022-02-08 20:31:13.684462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c76353265b'
down_revision = '8208fdc3ea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pokeparty', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokeparty', type_='unique')
    # ### end Alembic commands ###
