"""empty message

Revision ID: 6624c271cd77
Revises: 31f468d31ee5
Create Date: 2022-02-07 21:27:07.023757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6624c271cd77'
down_revision = '31f468d31ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokeuserjoin', sa.Column('pokeparty_id', sa.Integer(), nullable=True))
    op.alter_column('pokeuserjoin', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('pokeuserjoin_poke_id_fkey', 'pokeuserjoin', type_='foreignkey')
    op.create_foreign_key(None, 'pokeuserjoin', 'pokeparty', ['pokeparty_id'], ['id'])
    op.drop_column('pokeuserjoin', 'poke_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokeuserjoin', sa.Column('poke_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pokeuserjoin', type_='foreignkey')
    op.create_foreign_key('pokeuserjoin_poke_id_fkey', 'pokeuserjoin', 'pokeparty', ['poke_id'], ['id'])
    op.alter_column('pokeuserjoin', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pokeuserjoin', 'pokeparty_id')
    # ### end Alembic commands ###
