"""empty message

Revision ID: 7160327b0aa9
Revises: cd05ae51ab6f
Create Date: 2022-02-08 08:18:47.556787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7160327b0aa9'
down_revision = 'cd05ae51ab6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puj', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('puj', sa.Column('pokeparty_id', sa.Integer(), nullable=True))
    op.drop_constraint('puj_party_id_fkey', 'puj', type_='foreignkey')
    op.create_foreign_key(None, 'puj', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'puj', 'pokeparty', ['pokeparty_id'], ['id'])
    op.drop_column('puj', 'party_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puj', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'puj', type_='foreignkey')
    op.drop_constraint(None, 'puj', type_='foreignkey')
    op.create_foreign_key('puj_party_id_fkey', 'puj', 'user', ['party_id'], ['id'])
    op.drop_column('puj', 'pokeparty_id')
    op.drop_column('puj', 'user_id')
    # ### end Alembic commands ###
