"""empty message

Revision ID: 8208fdc3ea47
Revises: 7160327b0aa9
Create Date: 2022-02-08 17:10:02.569268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8208fdc3ea47'
down_revision = '7160327b0aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke_user_join',
    sa.Column('pokeparty_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokeparty_id'], ['pokeparty.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokeparty_id', 'user_id')
    )
    op.drop_table('puj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puj',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pokeparty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pokeparty_id'], ['pokeparty.id'], name='puj_pokeparty_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='puj_user_id_fkey')
    )
    op.drop_table('poke_user_join')
    # ### end Alembic commands ###
