"""empty message

Revision ID: a741dd411542
Revises: 071b4b899b72
Create Date: 2022-02-11 17:06:24.493121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a741dd411542'
down_revision = '071b4b899b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('battles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'battles')
    # ### end Alembic commands ###
