"""empty message

Revision ID: cd05ae51ab6f
Revises: 6939161c01e8
Create Date: 2022-02-07 21:45:21.627664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd05ae51ab6f'
down_revision = '6939161c01e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puj',
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['user.id'], )
    )
    op.drop_table('pokeuserjoin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokeuserjoin',
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['user.id'], name='pokeuserjoin_party_id_fkey')
    )
    op.drop_table('puj')
    # ### end Alembic commands ###
